version: '3'
services:
  service1:
    build: 
      context: ./service1
      dockerfile: Dockerfile
    command: sleep 100
    ports:
      - "5000:5000"
    volumes:
      - .:/workspace
    links:
      - service2
  
  service2:
    build: 
      context: ./service2
      dockerfile: Dockerfile
    command: sleep 100
    volumes:
      - .:/workspace

  service3:
    image: "markliou/python3-tensorflow-gpu"
    command: sleep 100


